services:

  postgres:
    image: postgres:16-alpine
    container_name: network-monitor-db
    environment:
      POSTGRES_DB: network_monitor
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    container_name: network-monitor-backend
    environment:
      DB_HOST: postgres
      DB_USER: postgres
      DB_PASSWORD: postgres
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy

  frontend:
    build: ./network-monitor-frontend
    container_name: network-monitor-frontend
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  postgres_data:
  